version: "3"

services:
  app:
    build: .
    # entrypoint: ./.docker/entrypoint.sh
    command: tail -f /dev/null
    container_name: if3-desafio2-frontend-app
    ports:
      - 3001:3000
    volumes:
      - .:/home/node/app
    extra_hosts: 
      - 'host.docker.internal:172.17.0.1'
