version: '3'

services:
  api:
    build: ./api
    container_name: if3-desafio2-api
    ports:
      - 3000:3000
    volumes:
      - ./api:/home/node/app
    extra_hosts: 
      - 'host.docker.internal:172.17.0.1'
    entrypoint: .docker/entrypoint.sh

  frontend:
    build: ./frontend
    entrypoint: .docker/entrypoint.sh
    container_name: if3-desafio2-frontend
    ports:
      - 3001:3000
    volumes:
      - ./frontend:/home/node/app
    extra_hosts: 
      - 'host.docker.internal:172.17.0.1'