version: '3'

services:
  app:
    build: .
    command: tail -f /dev/null
    container_name: if3-desafio2-api-app
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
    extra_hosts: 
        - 'host.docker.internal:172.17.0.1'